---

- hosts: app
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:
    - name: stop nginx on app
      service:
        name: nginx
        state: stopped

    - name: install apache2
      apt:
        name: apache2
        state: latest

    - name: start apache2 on app
      service:
        name: apache2
        state: started
